# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

contas=[]
def criar_conta():
        verificador_conta_existe = False
        dados_nova_conta = {}
        dados_nova_conta["numero_conta"] = input("Digite o numero da nova conta: \n>>>>")

        for conta_em_consulta in contas:
            if conta_em_consulta ["numero_conta"] == dados_nova_conta["numero_conta"]:
               verificador_conta_existe = True
            break

        if verificador_conta_existe== True:
            print("\nO numero da conta ja existe. Tente novemente. ")
        else:
            dados_nova_conta["saldo_conta"] = float (input("Digite o saldo da nova conta \n>>>"))
            contas.append(dados_nova_conta)
            print("\nOperacao efetuada com sucesso")

def remover_conta():
        numero_conta = input(" Digite o numero da conta para remover \n>>")
        conta_encontrada = False
        for  conta_em_consulta in contas:
         if  conta_em_consulta["numero_conta"] == numero_conta:
          conta_encontrada = True
          contas.remove(conta_em_consulta)
          print("\nOpereacao efetuada com sucesso")
          break

        if not conta_encontrada:
         print("\nO numero da conta nao existe. tente novamente ")

def listar_contas():
        if len(contas) == 0:
         print("\nNao ha contas cadastradas")
        else:
         index = 1
         for conta_em_consulta in contas:
            if conta_em_consulta["saldo_conta"] >=0:
             status = "Positivo"
            else:
             status = "Negativo"
            print(f'{index} - Numero da conta: {conta_em_consulta["numero_conta"]} / Saldo da conta: R$ {conta_em_consulta["saldo_conta"] :.2f} ({status})')
            index += 1


def adicionar_saldo_em_conta():
    numero_conta = input("Digite o numero da conta: \n>>>")
    for conta_em_consulta in contas:
        if conta_em_consulta["numero_conta"] == numero_conta:
         valor_credito = float(input("Digite o valor do credito \n>>> R$"))
        if valor_credito < 0:
            print("\nValores negativo nao sao aceitos. Tente novamente.")
            return
        else:
            conta_em_consulta["saldo_conta"] += valor_credito
            print("\nOperacao efetuada com sucesso")
            return
    print("\nO numero da conta nao foi encontrado. Tente novamente. ")

def remover_saldo_em_conta():
     numero_conta = input("Digite o numero da conta: \n>>>")
     for conta_em_consulta in contas:
        if conta_em_consulta["numero_conta"] == numero_conta:
         valor_debito = float(input("Digite o valor do debito \n>>> R$"))
        if valor_debito < 0:
            print("\nValores negativo nao sao aceitos. Tente novamente.")
            return
        else:
            conta_em_consulta["saldo_conta"] -= valor_debito
            print("\nOperacao efetuada com sucesso")
            return
     print("\nO numero da conta nao foi encontrado. Tente novamente. ")

def transferir_saldo_entre_contas():
    conta_partida = input("Digite o numero da sua conta: \n>>>")
    verificador_etapa = 0
    # procurar a primeira conta
    for conta_em_consulta in contas:
        if conta_em_consulta["numero_conta"] == conta_partida:
           verificador_etapa = 1
           conta_destino = input("Digite o numero da conta destino:\n>>")
    # verificar se e uma transferencia para a mesma conta
           if conta_destino != conta_partida:
    # procurar a segunda conta
               for conta_destino_em_consulta in contas:
                   if conta_destino_em_consulta["numero_conta"] == conta_destino:
                       verificador_etapa = 3
                       valor_transferencia = float(input("Digite o valor da transferencia \n>>> R$ "))
    # verifica se o saldo e suficiente
                       if  valor_transferencia > conta_destino_em_consulta ["saldo_conta"]:
                           print("\nNao e possivel transferir um valor maior que o seu saldo ")
                           break
    # verifica se o valor e negativo
                       elif valor_transferencia <0:
                            print("\nNao e possivel tranferir um valor negativo")
                            break
                       else:
                           conta_em_consulta["saldo_conta"] -= valor_transferencia
                           conta_destino_em_consulta["saldo_conta"]  += valor_transferencia
                           print("\nOperacao efetuada com sucesso")
                           break

           else:
               verificador_etapa = 2
               break

    if verificador_etapa == 0:
        print("\nA sua conta nao foi encontrada. Tente novamente.")
    elif verificador_etapa == 1:
        print("\nAconta de destino nao foi encontrada. Tente novamente ")
    elif verificador_etapa == 2:
        print("\nNao e possivekl transferir dinheiro para a mesma conta.")



def consultar_saldo_de_conta():
    numero_conta = input("Digite o numero de uma conta para consutar o saldo: \n>>>")
    for conta_em_consulta in contas:
        if conta_em_consulta ["numero_conta"] == numero_conta:
            if conta_em_consulta["saldo_conta"] >= 0:
                status = "Positivo"
            else:
                status = "Negativo"
            print(f'\nO saldo e : R${conta_em_consulta["saldo_conta"]:.2f} ({status})')
            return
    print("\nO numero da conta nao foi encontrado. Tente novamente.")


print(">>> Bem vindo ao sistema Bancario <<<")


while True:
    #print(contas)
    print("\n### Menu ###")
    print("0 - Sair")
    print("1 - Criar Uma nova Conta ")
    print("2 - Remover Uma Conta ")
    print("3 - Listar todas as contas ")
    print("4 - Adicionar Saldo (creditar) ")
    print("5 - Remover Saldo (debitar) ")
    print("6 - Tranferiar valor entre contas ")
    print("7 - Consultar saldo de uma conta")
    numero_operacao = input("selecione a operacao que deseja realizar: \n>>>")

    if numero_operacao == "0":
        print("\nSistema encerrado")
        break
# operacao 1 - criar uma nova conta
    elif numero_operacao == "1":
        criar_conta()


# operacao 2 - remover uma conta
    elif numero_operacao == "2":
        remover_conta()


# operacao 3 - listar todas as contas
    elif numero_operacao == "3":
        listar_contas()

# operacao 4 - adicionar Saldo
    elif numero_operacao == "4":
        adicionar_saldo_em_conta()


# operacao 5- Remover Saldo
    elif numero_operacao == "5":
        remover_saldo_em_conta()

# operacao 6- Traneferir valor entre contas
    elif numero_operacao == "6":
        transferir_saldo_entre_contas()

# operacao 7- consultar saldo de uma conta
    elif numero_operacao == "7":
       consultar_saldo_de_conta()

    else:
        print("\nOperacao invalida")